### ISSUE TITLE
How change icon from toolbar ?

### ISSUE THREAD

**Issue by artsx** [fritz-c/react-image-lightbox#31]
Hello,
I would like to change the icons on the toolbar because I changed the CSS and my background is white, I can't change the icons as they are image.
Do you have a solution ?

I would either use the icons or materials are-awesome power or coloring

Best regards,

**Comment by fritz-c** [comment]
I don't have the time to write all the details up right now, but basically what I would do is get the url string for the icon, decode it from base64 using `atob(<base64 string here>)`, change the color to black in the appropriate place, encode to base64 again with `btoa(<your svg string here>)` and then use that url for the `background-image`.
```css
.ril-zoom-in {
    background-image: url(data:image/svg+xml;base64,YOUR_BASE64_ENCODED_SVG_STRING_HERE) !important;
}
```
Unfortunately, before I finish refactoring things, the `!important` is probably necessary.
