### ISSUE TITLE
Close button invisible

### ISSUE THREAD

**Issue by sandervanhooft** [fritz-c/react-image-lightbox#33]
I have dropped the example code provided with react-image-lightbox v3.1.0 in my project, all works fine, but the close button is invisible. The zoom buttons are visible (and functional) though.

From the browser element inspector:
```
<li class="ril-toolbar__item toolbarItem___3WbMb">
    <button type="button" class="close ril-close ril-toolbar__item__child toolbarItemChild___2U_MP builtinButton___1zqo6 closeButton___3BdAF"></button>
</li>
```

Am I missing something, any clue?

Edit: I can click the close button, but there's no icon.

**Comment by fritz-c** [comment]
If you're using bootstrap, it's quite possible that the `.close` class is getting overwritten. Looking back now, I'm not sure why I used such a generic name for that button. As a rough fix until I remove the deprecated `.close` in v4.0, you can take the style for the close button and give it `!important`. Like so (untested):
```css
.ril-close {
    background: url(data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zd…UgLTEuMjUsLTEuMjUgNy41LC03LjUgLTcuNSwtNy41IHoiIGZpbGw9IiNGRkYiLz48L3N2Zz4=) no-repeat 50% !important;
}
```

Please let me know if that does it for you.

**Comment by sandervanhooft** [comment]
Hi @fritz-c, thanks for your response. I was not able to get it to work.

1.  I guess you're right on the collision with Bootstrap.
2. Is it possible you've pasted a shortened (invalid) url? The browser console / github may clip it (I notice a '...' in the string).

I get this error:

```
[Error] Failed to load resource: Data URL decoding failed (data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zd…UgLTEuMjUsLTEuMjUgNy41LC03LjUgLTcuNSwtNy41IHoiIGZpbGw9IiNGRkYiLz48L3N2Zz4=)
```

**Comment by fritz-c** [comment]
Ah, sorry about that. I copied that data url from the Chrome console. Try this one:
```css
.ril-close {
    background: url('data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZlcnNpb249IjEuMSIgd2lkdGg9IjIwIiBoZWlnaHQ9IjIwIj48cGF0aCBkPSJtIDEsMyAxLjI1LC0xLjI1IDcuNSw3LjUgNy41LC03LjUgMS4yNSwxLjI1IC03LjUsNy41IDcuNSw3LjUgLTEuMjUsMS4yNSAtNy41LC03LjUgLTcuNSw3LjUgLTEuMjUsLTEuMjUgNy41LC03LjUgLTcuNSwtNy41IHoiIGZpbGw9IiNGRkYiLz48L3N2Zz4=') no-repeat center !important;
}
```
